# Generated by Django 4.0.2 on 2022-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_productdetails_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('section', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
